<a href="https://colab.research.google.com/github/JojoUce/DesarrolloTasks/blob/main/scrapy_PonceJoseph.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
# Instalación de las librerias o dependencias necesarias
!pip install beautifulsoup4 requests pandas
# beautifulsoup4 RECORRER ESTRUCTURAS DE PAGINAS WEB

Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (4.12.3)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (2.32.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4) (2.6)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests) (2024.8.30)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [79]:
# Importar dependencias necesarias para el análisis de datos y procesamiento de HTML
import json
import requests
import pandas as pd
from bs4 import BeautifulSoup as bs

In [80]:
# Función que convierte una lista de elementos en un DataFrame de Pandas
def rowsToDataFrame(rows):
    # Si el número de columnas no coincide, ajustamos el número de columnas al máximo encontrado
    max_cols = max(len(row) for row in rows)
    df = pd.DataFrame(rows[1:], columns=rows[0] + [''] * (max_cols - len(rows[0])))
    return df

In [81]:
# Función para extraer los datos de una tabla HTML y convertirla en una lista de listas
def processTableData(tbl):
    rows = []
    for child in tbl.find('tbody').children:
        row = []
        for td in child:
            try:
                item = td.text.replace('\n', '')
                if item:
                    row.append(item)
            except:
                continue
        if len(row) > 0:
            rows.append(row)
    return rows

In [100]:
# Leer contenido de la web con Requests
r = requests.get('https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)')

In [92]:
# Procesar el contenido HTML recuperado y convertirlo en una tabla de datos
soup = bs(r.content, 'html.parser')
tbl = soup.find_all('table', {'class': 'wikitable'})[0]

In [90]:
# Procesar la tabla y convertirla en una lista de listas
table = processTableData(tbl)

In [91]:
# Convertir la lista de filas de la tabla en un DataFrame de Pandas
df = rowsToDataFrame(table)

In [93]:
# Guardamos los datos extraídos en un archivo CSV para usarlos posteriormente
df.to_csv('countries_by_GDP.csv', index=False)

In [102]:
df.head(20)

,Country/Territory,IMF[1][13],World Bank[14],United Nations[15],,,
0,Forecast,Year,Estimate,Year,Estimate,Year,None
1,World,"110,047,109",2024,"105,435,540",2023,"100,834,796",2022
2,United States,"29,167,779",2024,"27,360,935",2023,"25,744,100",2022
3,China,"18,273,357",[n 1]2024,"17,794,782",[n 3]2023,"17,963,170",[n 1]2022
4,Germany,"4,710,032",2024,"4,456,081",2023,"4,076,923",2022
5,Japan,"4,070,094",2024,"4,212,945",2023,"4,232,173",2022
6,India,"3,889,130",2024,"3,549,919",2023,"3,465,541",2022
7,United Kingdom,"3,587,545",2024,"3,340,032",2023,"3,089,072",2022
8,France,"3,174,099",2024,"3,030,904",2023,"2,775,316",2022
9,Italy,"2,376,510",2024,"2,254,851",2023,"2,046,952",2022
10,Canada,"2,214,796",2024,"2,140,086",2023,"2,137,939",2022
11,Brazil,"2,188,419",2024,"2,173,666",2023,"1,920,095",2022
12,Russia,"2,184,316",2024,"2,021,421",2023,"2,240,422",2022
13,South Korea,"1,869,916",2024,"1,712,793",2023,"1,673,916",2022
14,Mexico,"1,848,125",2024,"1,788,887",2023,"1,463,323",2022
15,Australia,"1,802,006",2024,"1,723,827",2023,"1,776,577",2022
16,Spain,"1,731,469",2024,"1,580,695",2023,"1,415,874",2022
17,Indonesia,"1,402,590",2024,"1,371,171",2023,"1,319,100",2022
18,Turkey,"1,344,318",2024,"1,108,022",2023,"907,118",2022
19,Netherlands,"1,218,401",2024,"1,118,125",2023,"1,008,027",2022